### ISSUE TITLE
Crashes e bugs (repost)

### ISSUE THREAD

**Issue by Hypxwghost** [AlexandreSenpai/NHentai-app#1]
Não sei se meu celular é ruim ou oq,mas na maioria das vezes ocorre de as imagens nāo carregarem,ou carregarem e depois de certo tempo sumirem, também ocorre de tudo carregar normal e quando vc da scroll para baixo as imagens somem.
Hoje quando abri o aplicativo para testar aconteceu de travar tudo,aí não sei se a RAM do celular acabou ou oq,mas é isso.
Celular é um Samsung J320M(2016),bem velhinho,com Android desatualizado

Quando clico na imagem,pra aparecer em full-screen aparece normal,só acontece quando não esta em tela cheia,tipo quando vc abre algum Hent@i pra ver tipo um preview,igual tu mencionou na outra issue.
Malz por postar errado,sou novo por aqui!

![88401748-8222c680-cda0-11ea-8c1a-03b646b4d6dc](https://user-images.githubusercontent.com/60857997/89108676-a457bc80-d410-11ea-8b83-8c1570f56874.png)

# Sobre a parte de dar scroll e as imagens sumirem..
![lightshot_1596310808](https://user-images.githubusercontent.com/60857997/89109270-049d2d00-d416-11ea-938e-b4f5b98d8104.png)

# Após descer um pouco na página..
![lightshot_1596310776](https://user-images.githubusercontent.com/60857997/89109278-20a0ce80-d416-11ea-918d-cc5c00af26b4.png)

**Comment by AlexandreSenpai** [comment]
Aparentemente esses erros ocorrem pois havia um erro na API.
Estava hardcoded .jpg no fim de todas as urls, quando uma imagem era .png isso ocorria.
O mesmo fora corrigido hoje na versão v0.0.7 da API. 
Não fecharei a issue por enquanto, me atualize caso o erro persista.
